### ISSUE TITLE
Create Path Detection Algorithm

### ISSUE THREAD

**Issue by Jared-Chan** [ubc-subbots/triton#113]
Create a path detection algorithm in C++. Then integrate it into ROS2 by creating a `triton_path_marker` package and a `path_detector` node. The node should subscribe to the image topic of the down-facing camera and publish to a new topic the direction of the path marker. 

It can be based on the `triton_gate` package and use functions form the `triton_vision_utils` package. 

Path marker details: [RoboSub handbook](https://robonation.org/app/uploads/sites/4/2022/01/2022-RoboSub_Team-Handbook_v1.0.pdf) (P.14)

**Tasks**
- [ ] Detect a path marker and its direction in simple images. 

- [ ] Create a package `triton_path_marker` which will contain the component nodes needed to implement the algorithm. Don't worry about ROS2 at this stage, you could reating an auto generated node when you create the `triton_path_marker` package and in the main function of the node you can write the algorithm and run it by using `ros2 run`.

- [ ] Integrate the algorithm into a series of one or more ROS2 components nodes and test how they work in the pipeline.
