### ISSUE TITLE
Simple PID Tracking Controller

### ISSUE THREAD

**Issue by Jared-Chan** [ubc-subbots/triton#117]
Create a simple PID Tracking Controller described in Chapter 7 of **L. A. Gonzalez, DESIGN, MODELLING AND CONTROL OF AN AUTONOMOUS UNDERWATER VEHICLE. The University of Western Australia, 2004.** 

For now, assume that the desired pose is always updated and is in the local frame where the AUV is at the origin. 

It should at least subscribe to the following topics: (topic: message type)
- `/triton/controls/input_pose`: `geometry_msgs::msg::Pose`

It should publish to: 
- `/triton/controls/input_forces`: `geometry_msgs::msg::Wrench`

When the IMU plugin is implemented, the controller may also subscribe to it. 

Also, in the future, we may have a `/triton/state` topic that includes information of the AUV like position, orientation, velocity and acceleration. We may also make a trajectory generator, which would provide the desired velocity and acceleration. Before we have those, implement a PID controller that only uses the desired pose. 

**Tasks** 
- [ ] Determine the optimal number of PID controllers. (Only one for all movement or separate the degrees of freedom)
- [ ] Determine what additional information it needs, other than the desired pose
- [ ] Implement a simple PID controller, maybe one that only uses the 'P' of PID and controls only movement in the Z-axis. 
- [ ] Test the PID controller in Gazebo, by manually specifying a desired pose, or making a helper node to dynamically change the desired pose based on the current pose of the AUV
- [ ] Extend the PID controller to control more degrees of freedom
- [ ] Test the extended PID controller, potentially in a model world containing a gate and in conjunction with the gate detector.

**Comment by Jared-Chan** [comment]
For the desired velocity and acceleration, we can use a constant acceleration at the beginning, a constant velocity in the middle and a constant deceleration near the goal, like the graph around P.74 of https://robotics.ee.uwa.edu.au/theses/2004-AUV-Gonzalez.pdf at least until we have a better trajectory generator.
