### ISSUE TITLE
Create Package triton_teleop with Simple Keyboard Teleop Thrust Controller for Gazebo

### ISSUE THREAD

**Issue by loganfillo** [ubc-subbots/triton#17]
We need to create a teleoperation keyboard controller for Gazebo. This teleoperator should be able to be used on the physical AUV as well. There should be a new python package `triton_teleop` with a node `keyboard_teleop` in it. This node should do the following, accept user input from a keyboard, and publish the appropriate force command to a parameterised topic which deals with `geometry_msgs/msg/Wrench messages`.  The key layout should be the following, where X,Y,Z are forces

-     W/S : +X,-X
-     A/D: +Y,-Y
-     Q/Z: +Z,-Z

The keys should work as per the following example. When I press the W key, the positive X force published should be incremented by N_X (where N_X is either predetermined or parameterized and N_Y, N_Z also exist). As I continue to hold down the W key, the X force published is incremented by N_X every T secs (where T is a constant) until I release the W key. If I am holding both the W and A key down, both the X and Y forces will be incremented until I release their respective keys. While no keys are being pressed the last state of the X,Y,Z forces should be published.

**Resources**
[Pynput Docs on Keyboard Event Handling](https://pynput.readthedocs.io/en/latest/keyboard.html)
[Key Presses in Python](https://nitratine.net/blog/post/how-to-detect-key-presses-in-python/)

**Notes**
- The ROS2 dependency `pynput-pip` is needed as a package dependency to use pynput in that package.
- The force vector should simply act on the Gazebo model, in the future we will alter the teleoperator to be able to send forces to each thruster given a thrust allocation configuration.
- Read the documentation for `triton_gazebo` and test the teleoperator on the `cube` in `cube.world`

**Tasks**

- [ ] Create the package `triton_teleop` with python node `keyboard_teleop`

- [ ] Determine how to correctly handle the keyboard events with Pynput as stated above

- [ ] Create the publisher to publish the forces given by the keyboard events to the parameterized topic

- [ ] Test the teleoperator in Gazebo
