### ISSUE TITLE
Create Modular YOLO Object Detection Component Node

### ISSUE THREAD

**Issue by loganfillo** [ubc-subbots/triton#2]
We need to create a component node which is able to be loaded as part of a pipeline type, and which is able to detect objects given a YOLO model. The component should ideally be modular, in that it should be able to be configured with a given YOLO model either dynamically when running or statically when it is launched (probably easier and ideal). 

**Tasks**

- [x] Create a package `triton_object_recognition`  with required dependencies to use YOLO.

- [x] Create a component node `object_recognizer` in this package.

- [x] Have the component node listen to an image topic, and output location of all labelled objects and their location to a topic 

- [x] Have the component node be able to be configured with a YOLO model when it is launched either through a parameter or service.
