### ISSUE TITLE
Add Thrust Allocator Node Which Implements Thrust Allocation Algorithm in MATLAB

### ISSUE THREAD

**Issue by loganfillo** [ubc-subbots/triton#36]
We need to implement the thrust allocation algorithm we have designed in MATLAB so it can be used in ROS2. The node should be a standalone node with the option of being a component node.

**TASK**

- [x] Create new package `triton_control`

- [x] Implement node `thrust_allocator`, making sure to use a fast matrix libray (i.e Eigen)

- [x] Write unit tests to ensure the algorithm performs as required

**Comment by loganfillo** [comment]
Used opencv in c++ to calculate pseudoinverse using cv::invert() function. The node can be parameterised by a thruster configuration file, this functionality needs to be tested to ensure that this works.
