### ISSUE TITLE
Change triton_pipeline to Allow for Nodes from Multiple Packages in a Pipeline Config File

### ISSUE THREAD

**Issue by loganfillo** [ubc-subbots/triton#4]
We need to modify the `tr_pipeline` package so that the config file format allows a pipeline to be launched with component nodes from multiple packages. This should involve some sort of way of listing each component node of the pipeline in a way so that it is related to the package it comes from. The `pipeline_manager` should be changed so that its parameters reflect this new functionality and that the config file parsing is updated to reflect this change in parameters.

**Resources**
[ROS2 Params Design and Types](https://design.ros2.org/articles/ros_parameters.html)
[Understanding ROS2 Params (look at ros2 param dump)](https://index.ros.org/doc/ros2/Tutorials/Parameters/Understanding-ROS2-Parameters/)
[Using ROS2 Params in python](https://index.ros.org/doc/ros2/Tutorials/Using-Parameters-In-A-Class-Python/)

**Tasks**

- [x] Change `pipeline_manager`'s parameters so that the `components` parameters has the functionality to contain the name of a component and the package it is from. Remove the `pkg_name` parameter as this information is now on a per node basis.

- [x] Modify any pipeline config files to reflect this change in parameters

- [x] Modify `pipeline_manager` so that it now parses the config files correctly

- [x] Test that configuring and running the pipeline still works as before

**Comment by Over-TheRainbow** [comment]
Just so that you know, the pkg_name parameter in the .yaml config file has been replaced with a pkg_names parameter, where you would put a list which corresponds to the components, as we discussed earlier.
