### ISSUE TITLE
Create a State Management Node Which Can be Configured to Implement a FSM

### ISSUE THREAD

**Issue by loganfillo** [ubc-subbots/triton#6]
We need a way to manage our AUV's state autonomously. We need a node which is separate from the pipeline that is responsible for configuring and running the pipeline based on which state the AUV is supposed to be in.

**Resources**
[Finite State Machines](https://en.wikipedia.org/wiki/Finite-state_machine)
[Example ROS2 Python Projects](https://github.com/ros2/examples/tree/master/rclpy)
[Async vs Sync Client Calls **IMPORTANT**](https://index.ros.org/doc/ros2/Tutorials/Sync-Vs-Async/)

**Tasks**'

- [ ] Create a package `triton_state` with a python node (i.e `ros2 pkg create triton_state --node-name autonomous_state --build-type ament_python`)

- [ ] Make the node have a parameter of a list of strings, which is meant to be a successive transition of states

- [ ] Create a config directory to store .yml paramter files for a given state succession

- [ ] Create a launch file to launch the autonomous_state node parameterized by a given .yml 

- [ ] Implement the state transitions to make the node go through the succession of the states. For each state, it should call the configure pipeline service then use the run pipeline action given my the pipeline manager node. This should be done deterministically, which might be difficult given that a client is supposed to make calls asynchronously

**Comment by loganfillo** [comment]
See package example_client on branch logan/issue6 to see an example of how to run client calls deterministically. use the command `ros2 run example_client example_client node` to run, make sure pipline is launched as well
